ALTER TABLE uom_master ADD COLUMN IF NOT EXISTS symbol VARCHAR(20);
ALTER TABLE uom_master ADD COLUMN IF NOT EXISTS description VARCHAR(500);

INSERT INTO uom_master (code, name, symbol, base_uom, conversion_factor, active) VALUES
('NOS', 'Numbers', 'NOS', 'NOS', 1.0000, true),
('KG', 'Kilogram', 'KG', 'KG', 1.0000, true),
('G', 'Gram', 'G', 'KG', 0.0010, true),
('MG', 'Milligram', 'MG', 'KG', 0.000001, true),
('MT', 'Metric Ton', 'MT', 'KG', 1000.0000, true),
('MTR', 'Metre', 'MTR', 'MTR', 1.0000, true),
('CM', 'Centimetre', 'CM', 'MTR', 0.0100, true),
('MM', 'Millimetre', 'MM', 'MTR', 0.0010, true),
('FT', 'Feet', 'FT', 'MTR', 0.3048, true),
('INCH', 'Inch', 'INCH', 'MTR', 0.0254, true),
('SQM', 'Square Metre', 'SQM', 'SQM', 1.0000, true),
('SQFT', 'Square Feet', 'SQFT', 'SQM', 0.0929, true),
('L', 'Litre', 'L', 'L', 1.0000, true),
('ML', 'Millilitre', 'ML', 'L', 0.0010, true),
('GAL', 'Gallon', 'GAL', 'L', 3.7854, true),
('BOX', 'Box', 'BOX', 'BOX', 1.0000, true),
('PCS', 'Pieces', 'PCS', 'PCS', 1.0000, true),
('SET', 'Set', 'SET', 'SET', 1.0000, true),
('PAIR', 'Pair', 'PAIR', 'PAIR', 1.0000, true),
('DOZ', 'Dozen', 'DOZ', 'PCS', 12.0000, true),
('HRS', 'Hours', 'HRS', 'HRS', 1.0000, true),
('MIN', 'Minutes', 'MIN', 'HRS', 0.0167, true),
('SEC', 'Seconds', 'SEC', 'HRS', 0.0003, true),
('HR', 'Hour', 'HR', 'HRS', 1.0000, true),
('DAY', 'Day', 'DAY', 'DAY', 1.0000, true),
('WEEK', 'Week', 'WEEK', 'DAY', 7.0000, true),
('MONTH', 'Month', 'MONTH', 'DAY', 30.0000, true),
('ROL', 'Roll', 'ROL', 'ROL', 1.0000, true),
('BAG', 'Bag', 'BAG', 'BAG', 1.0000, true),
('LOT', 'Lot', 'LOT', 'LOT', 1.0000, true)
ON CONFLICT (code) DO NOTHING;
