--
-- V16__doc_links_and_dc_print_log.sql
-- DOCUMENT 02 v2.0 (Inventory FRS) — Traceability & DC Print audit tables
--
-- SCOPE:
--   (1) doc_links     — immutable cross-document reference links by internal ID
--                       (BR-INV-TRACE-2). Enables the Traceability Viewer (§03.3)
--                       to walk PO -> Inward -> GRN -> QC -> Issue -> DC -> Return
--                       without relying on display-number strings.
--   (2) dc_print_log  — immutable audit of every DC print event (FR-INV-DC-PRINT-1):
--                       doc_no, printed_by, printed_at, copy_number.
--
-- SAFETY:
--   - Identifiers are bigint identity (matches stock_ledger adopters).
--   - FK-free on purpose: document tables use heterogeneous class hierarchies, so
--     doc_links stores type discriminators instead of foreign keys, exactly like
--     stock_ledger.doc_type. Referential integrity lives in the application layer
--     (BR-INV-TRACE-1 postings are gated on source/target existence).
--   - Idempotent: CREATE TABLE IF NOT EXISTS.

CREATE TABLE IF NOT EXISTS public.doc_links (
    id               bigint NOT NULL,
    source_doc_id    bigint NOT NULL,
    source_doc_type  character varying(60) NOT NULL,
    target_doc_id    bigint NOT NULL,
    target_doc_type  character varying(60) NOT NULL,
    created_at       timestamp(6) with time zone,
    created_by       character varying(255),
    CONSTRAINT uq_doc_links_pair UNIQUE (source_doc_id, source_doc_type, target_doc_id, target_doc_type)
);

ALTER TABLE public.doc_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.doc_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX IF NOT EXISTS idx_doc_links_source ON public.doc_links (source_doc_id, source_doc_type);
CREATE INDEX IF NOT EXISTS idx_doc_links_target ON public.doc_links (target_doc_id, target_doc_type);

CREATE TABLE IF NOT EXISTS public.dc_print_log (
    id          bigint NOT NULL,
    doc_no      character varying(60) NOT NULL,
    doc_type    character varying(60),
    printed_by  character varying(255) NOT NULL,
    printed_at  timestamp(6) with time zone NOT NULL DEFAULT now(),
    copy_number integer NOT NULL DEFAULT 1
);

ALTER TABLE public.dc_print_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dc_print_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE INDEX IF NOT EXISTS idx_dc_print_log_doc_no ON public.dc_print_log (doc_no);