ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS brand VARCHAR(200);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS machine_cost NUMERIC(14,2);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS gst_rate NUMERIC(5,2);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS gst_amount NUMERIC(14,2);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS total_cost_with_gst NUMERIC(14,2);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS controller_brand VARCHAR(100);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS spindle_speed INTEGER;
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS spindle_power NUMERIC(10,2);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS tool_capacity VARCHAR(100);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS max_machining_dia NUMERIC(10,2);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS max_machining_length NUMERIC(10,2);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS x_axis_travel NUMERIC(10,2);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS y_axis_travel NUMERIC(10,2);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS z_axis_travel NUMERIC(10,2);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS rapid_traverse NUMERIC(10,2);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS tailstock_type VARCHAR(100);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS tailstock_stroke NUMERIC(10,2);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS quill_diameter NUMERIC(10,2);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS quill_taper VARCHAR(50);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
ALTER TABLE machine_master ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

UPDATE machine_master SET brand = manufacturer WHERE brand IS NULL AND manufacturer IS NOT NULL;
UPDATE machine_master SET controller_brand = control_type WHERE controller_brand IS NULL AND control_type IS NOT NULL;
UPDATE machine_master SET spindle_power = power_rating_kw WHERE spindle_power IS NULL AND power_rating_kw IS NOT NULL;
UPDATE machine_master SET spindle_speed = spindle_speed_rpm WHERE spindle_speed IS NULL AND spindle_speed_rpm IS NOT NULL;
UPDATE machine_master SET x_axis_travel = travel_x_mm WHERE x_axis_travel IS NULL AND travel_x_mm IS NOT NULL;
UPDATE machine_master SET y_axis_travel = travel_y_mm WHERE y_axis_travel IS NULL AND travel_y_mm IS NOT NULL;
UPDATE machine_master SET z_axis_travel = travel_z_mm WHERE z_axis_travel IS NULL AND travel_z_mm IS NOT NULL;
UPDATE machine_master SET machine_cost = purchase_cost WHERE machine_cost IS NULL AND purchase_cost IS NOT NULL;
