create table app_users (id bigserial primary key, username varchar(80) unique not null, password varchar(100) not null, role varchar(40));
create table item_master (id bigserial primary key, code varchar(60) unique not null, description varchar(200) not null, uom varchar(20), category varchar(60), default_rate double precision, safety_stock double precision, requires_batch boolean, requires_heat boolean, active boolean);
create table party_master (id bigserial primary key, kind varchar(20) not null, code varchar(60) unique not null, name varchar(120) not null);
create table location_master (id bigserial primary key, code varchar(60) unique not null);
create table ref_docs (id bigserial primary key, kind varchar(10) not null, number varchar(60) unique not null, ref_code varchar(60), status varchar(20));
create table erp_documents (id bigserial primary key, doc_type varchar(60) not null, doc_no varchar(60) not null, status varchar(20) not null, doc_date date, body jsonb not null default '{}', created_by varchar(80), created_at timestamp, updated_at timestamp);
create index idx_doc_type_status on erp_documents(doc_type, status);
create index idx_doc_no on erp_documents(doc_no);
create table stock_ledger (id bigserial primary key, tx_date date, doc_no varchar(60), doc_type varchar(60), tx_type varchar(60), item_code varchar(60), location varchar(60), batch_no varchar(60), heat_no varchar(60), in_qty double precision, out_qty double precision);
create index idx_ledger_item_loc on stock_ledger(item_code, location);