-- P8 CAPABILITY A — Multiple-Output Production Entry (FR-PROD-ENTRY-003, BK-013).
--
-- ADDITIVE ONLY. No existing table/data is altered.
--
-- production_entry carries exactly one primary-output set (good/rejected/rework/scrap for
-- part_code); a machining operation can also yield a co-part or by-product (e.g. swarf).
-- This child table records those ADDITIONAL outputs authoritatively (ADR-001: production_entry*
-- stays the source of truth; prod_output_event remains the flag-gated derived projection).
--
-- The natural key (production_entry_id, output_type, item_code, location) mirrors the committed
-- prod_output_event key (session_id, operation_event_id, output_type, item_code, location) so the
-- derived projection replays without key mapping and stays idempotent.
--
-- Co/by-product rows are recording-only facts; they NEVER drive StockService postings (ADR-005
-- boundary), WIP, pending, produced, or subjob-progress (CLAR-002 contract refers exclusively to
-- the primary stage quantities).

CREATE TABLE IF NOT EXISTS production_entry_output (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_entry_id    BIGINT NOT NULL,
    output_type            VARCHAR(30) NOT NULL,
    item_code              VARCHAR(60) NOT NULL,
    item_name              VARCHAR(200),
    uom                    VARCHAR(20),
    location               VARCHAR(60) NOT NULL DEFAULT 'STORE',
    quantity               NUMERIC(18,4) NOT NULL,
    weight                 NUMERIC(14,4),
    destination_stage_code VARCHAR(60),
    remarks                VARCHAR(255),
    created_at             TIMESTAMP(6) WITH TIME ZONE DEFAULT now(),
    CONSTRAINT uq_production_entry_output_key UNIQUE (production_entry_id, output_type, item_code, location),
    CONSTRAINT ck_production_entry_output_qty_positive CHECK (quantity > 0),
    CONSTRAINT fk_production_entry_output_entry FOREIGN KEY (production_entry_id)
        REFERENCES production_entry(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_production_entry_output_entry
    ON production_entry_output(production_entry_id);