package in.zygertechnology.zygererp;

import in.zygertechnology.zygererp.entity.AppUser;
import in.zygertechnology.zygererp.repo.UserRepository;
import in.zygertechnology.zygererp.security.JwtService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.test.context.ActiveProfiles;
import org.testcontainers.junit.jupiter.Testcontainers;

/**
 * Shared base for integration tests that run against a real, isolated PostgreSQL
 * Testcontainer. Concrete subclasses declare their own static
 * {@code @Container @ServiceConnection PostgreSQLContainer} so each test class
 * binds to its own database and Spring context (avoids a shared-container /
 * cached-context lifecycle race when multiple classes run in one suite).
 *
 * <p>Provides real end-to-end authentication against the application's own
 * JWT/security layer: {@link #adminToken()} persists an ADMIN user into the
 * isolated database and returns a token signed by the real {@link JwtService}
 * (and therefore validated by the real {@code JwtAuthFilter}). No security
 * layer is bypassed or stubbed.</p>
 */
@SpringBootTest
@AutoConfigureMockMvc
@Testcontainers
@ActiveProfiles("test")
public abstract class AbstractPostgresIntegrationTest {

    private static final String ADMIN_USERNAME = "integration-admin";

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private JwtService jwtService;

    /**
     * Returns a valid access token for an ADMIN user persisted in the isolated
     * database. The token is generated by the application's real JwtService,
     * so it is accepted by the production security filter chain.
     */
    protected String adminToken() {
        if (!userRepository.existsByUsername(ADMIN_USERNAME)) {
            AppUser admin = AppUser.builder()
                    .username(ADMIN_USERNAME)
                    .password(passwordEncoder.encode("Integration-Admin-123!"))
                    .fullName("Integration Admin")
                    .email("integration-admin@zyger.in")
                    .role("ADMIN")
                    .status("ACTIVE")
                    .active(true)
                    .build();
            userRepository.save(admin);
        }
        return jwtService.generate(ADMIN_USERNAME, "ADMIN");
    }
}
