package in.zygertechnology.zygererp.controller;

import in.zygertechnology.zygererp.AbstractPostgresIntegrationTest;
import tools.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;

import java.util.Map;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Integration tests for SalesController.
 * Runs against an isolated PostgreSQL Testcontainer and authenticates with a real
 * JWT generated by the application's JwtService (see AbstractPostgresIntegrationTest),
 * so every request exercises the real security layer.
 */
@DisplayName("Sales Controller Integration Tests")
class SalesControllerIntegrationTest extends AbstractPostgresIntegrationTest {

    @Container
    @ServiceConnection
    static final PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    private String bearer(String token) {
        return "Bearer " + token;
    }

    @Test
    @DisplayName("GET /api/v1/sales/dashboard - should return dashboard stats")
    void shouldReturnDashboard() throws Exception {
        mockMvc.perform(get("/api/v1/sales/dashboard")
                        .header("Authorization", bearer(adminToken())))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.totalSO").exists())
                .andExpect(jsonPath("$.pendingApproval").exists());
    }

    @Test
    @DisplayName("GET /api/v1/sales/{type} - should list sales orders")
    void shouldListSalesOrders() throws Exception {
        mockMvc.perform(get("/api/v1/sales/sales-order")
                        .header("Authorization", bearer(adminToken()))
                        .param("page", "0")
                        .param("size", "10"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content").isArray())
                .andExpect(jsonPath("$.totalElements").isNumber());
    }

    @Test
    @DisplayName("GET /api/v1/sales/{type} - should reject unknown document type")
    void shouldRejectUnknownType() throws Exception {
        mockMvc.perform(get("/api/v1/sales/unknown-type")
                        .header("Authorization", bearer(adminToken())))
                .andExpect(status().isBadRequest());
    }

    @Test
    @DisplayName("POST /api/v1/sales/{type} - should create sales order")
    void shouldCreateSalesOrder() throws Exception {
        Map<String, Object> body = Map.of(
                "customer", "Test Customer",
                "orderDate", "2026-09-01",
                "lines", java.util.List.of()
        );

        mockMvc.perform(post("/api/v1/sales/sales-order")
                        .header("Authorization", bearer(adminToken()))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(body)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.docNo").exists())
                .andExpect(jsonPath("$.status").value("DRAFT"));
    }

    @Test
    @DisplayName("GET /api/v1/sales/{type}/next-number - should return next number")
    void shouldReturnNextNumber() throws Exception {
        mockMvc.perform(get("/api/v1/sales/sales-order/next-number")
                        .header("Authorization", bearer(adminToken())))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.nextNumber").exists());
    }

    @Test
    @DisplayName("GET /api/v1/sales/{type}/export - should export to xlsx")
    void shouldExportSalesOrders() throws Exception {
        mockMvc.perform(get("/api/v1/sales/sales-order/export")
                        .header("Authorization", bearer(adminToken()))
                        .param("format", "xlsx"))
                .andExpect(status().isOk())
                .andExpect(content().contentType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"));
    }

    @Test
    @DisplayName("GET /api/v1/sales/proforma-invoice - should list proforma invoices")
    void shouldListProformaInvoices() throws Exception {
        mockMvc.perform(get("/api/v1/sales/proforma-invoice")
                        .header("Authorization", bearer(adminToken())))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content").isArray());
    }

    @Test
    @DisplayName("GET /api/v1/sales/sales-dc - should list delivery challans")
    void shouldListDeliveryChallans() throws Exception {
        mockMvc.perform(get("/api/v1/sales/sales-dc")
                        .header("Authorization", bearer(adminToken())))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content").isArray());
    }

    @Test
    @DisplayName("GET /api/v1/sales/sales-invoice - should list sales invoices")
    void shouldListSalesInvoices() throws Exception {
        mockMvc.perform(get("/api/v1/sales/sales-invoice")
                        .header("Authorization", bearer(adminToken())))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.content").isArray());
    }
}
